### ISSUE TITLE
Docker NextJS

### ISSUE THREAD

**Issue by ColoDidac** [JoanPalau/lo-mercat#102]
*As a* Developer
*I want to* create a Docker for NextJs App
*In order to* get an easy deploy configuration

***
**Requirements**
* Have installed Docker

**Task Completion Checklist**
- [ ] Completed flow on Mobile
- [ ] Test flow on Mobile
- [ ] Screenshot on Mobile
- [ ] Completed flow on Web
- [ ] Test flow on Web
- [ ] Screenshot on Web

**Comment by josalhor** [comment]
Duplicated #106
