### ISSUE TITLE
Internalisation

### ISSUE THREAD

**Issue by CristianColavito** [JoanPalau/lo-mercat#118]
*As a Everyone*
*I want to view the app in english and spanish*
*In order to have another language*

***
**Requirements**

**Dependencies**

**Task Completion Checklist**
- [x] Completed flow on Mobile
- [x] Test flow on Mobile
- [x] Screenshot on Mobile
- [x] Completed flow on Web
- [x] Test flow on Web
- [x] Screenshot on Web

**Comment by JoanPalau** [comment]
Added dependencies and provided some examples to implement in all pages.
