### ISSUE TITLE
Usability prototype Farmer on Mobile

### ISSUE THREAD

**Issue by josalhor** [JoanPalau/lo-mercat#135]
# Overview
This is a story that summarizes all the usability prototype issues for the Farmer on Mobile

# Features
- [ ] Set Stock
- [ ] Add to Market
- [ ] Login
- [ ] Landing
- [ ] Check Orders
- [ ] Others

# Useful links
* Visual design
* Api definition
* Other links...

**Comment by ColoDidac** [comment]
Hello, Today 18/11 I close this issue, its already done
