### ISSUE TITLE
Split adminJS from main app

### ISSUE THREAD

**Issue by JoanPalau** [JoanPalau/lo-mercat#138]
*As a* developer
*I want to* split the adminJS interface from the main app
*In order to* provide less dependencies and do independent deployments of both apps

***
**Requirements**
* Create a new folder called superadmin
* Move the adminJS related codebase to the new folder
* Remove adminJS dependencies form the main app package.json

**Dependencies**
None

**Task Completion Checklist**
- [ ] AdminJS works independently from lo-mercat main app
- [ ] Main app works

**Comment by josalhor** [comment]
Closed as won't fix and/or future work
