### ISSUE TITLE
Enable market creation

### ISSUE THREAD

**Issue by JoanPalau** [JoanPalau/lo-mercat#33]
*As a* superadmin
*I want to* be able to create a new farmer's market
*In order to* enable new farmer's stands to the platform

***
**Requirements**
* I have a simple interface where I can add the market basic information
* Market basic information (name, place, ocurrency, image, coordinates, description, stands)

**Dependencies**
* #3

**Task Completion Checklist**
- [ ] Completed flow on Mobile
- [ ] Test flow on Mobile
- [ ] Screenshot on Mobile
- [ ] Completed flow on Web
- [ ] Test flow on Web
- [ ] Screenshot on Web

**Comment by josalhor** [comment]
Closed as won't fix and/or future work
