### ISSUE TITLE
Sign in as a SuperAdmin

### ISSUE THREAD

**Issue by JoanPalau** [JoanPalau/lo-mercat#68]
*As a* Superadmin
*I want to* be able to sign in 
*In order to* acces to the platform

***
**Requirements**
* Having a admin acces

**Dependencies**
*  

**Task Completion Checklist**
- [ ] Completed flow on Mobile
- [ ] Test flow on Mobile
- [ ] Screenshot on Mobile
- [ ] Completed flow on Web
- [ ] Test flow on Web
- [ ] Screenshot on Web

**Comment by josalhor** [comment]
Closed as won't fix and/or future work
