### ISSUE TITLE
Style not loading

### ISSUE THREAD

**Issue by ColoDidac** [JoanPalau/lo-mercat#79]
**Describe the bug**
When you get a page with a reference to another, and you go to this one, when you return will not have  the styles loadeds.

**To Reproduce**
1. Go to 'any page'
2. Click on 'back button'
4. See error with the styles

**Expected behavior**
The components should have the css files.

**Screenshots**
No need it.

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome
 - Version latest

**Comment by JoanPalau** [comment]
Hello, the issue should be fixed with the introduction of styled components
